#!/bin/sh

if [ -e /sys/class/gpio/gpio115 ]; then
	echo 115 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio115/direction
	echo 1 > /sys/class/gpio/gpio115/value
fi

if [ -e /sys/class/gpio/gpio110 ]; then
	echo 110 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio110/direction
	echo 1 > /sys/class/gpio/gpio110/value
fi

if [ -e /sys/class/gpio/gpio114 ]; then
	echo 114 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio114/direction
	echo 0 > /sys/class/gpio/gpio114/value
fi

ip link set can0 down
ip link set can0 type can bitrate 50000 triple-sampling on
ip link set can0 up

echo ""
echo "examples:"
echo "cansend can0 500#1E.10.10"
echo "candump can0"
