# Copyright (C) 2014 Oliver Stäbler <oliver.staebler@bytesatwork.ch>
# Released under the MIT license (see COPYING.MIT for the terms)

require conf/distro/poky.conf
DISTRO = "poky-bytesatwork"

MAINTAINER = "<yocto@bytesatwork.ch>"

POKY_DEFAULT_EXTRA_RDEPENDS = ""
POKY_DEFAULT_EXTRA_RRECOMMENDS = ""

POKY_DISTRO_FEATURES  = "alsa ipv4 ipv6 largefile xattr"
DISTRO_FEATURES = "${DISTRO_FEATURES_LIBC_DEFAULT} ${POKY_DISTRO_FEATURES}"

TCLIBCAPPEND = ""

INIT_MANAGER = "systemd"

PACKAGE_CLASSES = "package_deb"
PACKAGE_FEED_URIS = "http://packages.bytesatwork.io/yocto/${DISTRO_VERSION}/${MACHINE}"

# Prevent /etc/timestamp to have a fixed/old value as this prevents the package
# stream to work, as the 'Release' will not yet be valid.
REPRODUCIBLE_TIMESTAMP_ROOTFS = ""

ROOT_HOME = "/root"

INHERIT += "image-buildinfo"
IMAGE_BUILDINFO_VARS = "MACHINE DISTRO DISTRO_VERSION IMAGE_BASENAME DATETIME"
